version: '3.8'

services:
  yusi-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: yusi-front:latest
    container_name: yusi-front
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 高德地图 JS API Key（用于加载地图SDK）
      - AMAP_JS_KEY=${AMAP_JS_KEY}
      # 高德地图安全密钥（用于 Nginx 代理转发，更安全）
      - AMAP_SECURITY_CODE=${AMAP_SECURITY_CODE}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
    external: true
